### PR TITLE
Fixes build issues which occur when building on Apple Silicon

### LINKED ISSUE #74: `docker: Error response from daemon: pull access denied for xeus-clang-repl`
```
(base) mlevental@maksims-MacBook-Pro xeus-clang-repl % docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
(base) mlevental@maksims-MacBook-Pro xeus-clang-repl % ./run-docker.sh
-:33 SC2046 warning: Quote this to prevent word splitting.
...
-:158 SC2086 info: Double quote to prevent globbing and word splitting.

Container engine initialization error: ('Check if docker is running on the host.', DockerException("Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"))
Unable to find image 'xeus-clang-repl:latest' locally
docker: Error response from daemon: pull access denied for xeus-clang-repl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Can't find it on [dockerhub](https://hub.docker.com/search?q=xeus-clang-repl) nor here as a package. 

Note, maybe I need to build the image locally first (which is fine) but then the [README](https://github.com/compiler-research/xeus-clang-repl#xeus-clang-repl) should be updated...

cc @vgvassilev

### LINKED ISSUE #75: Dockerfile doesn't support other platforms (e.g., arm64/m1)
In working around https://github.com/compiler-research/xeus-clang-repl/issues/74, I try to build the docker image (`docker build . -t xeus-clang-repl`) but fail to because of a linker error during building `CppInterOp`:

```
282.9 -- Build files have been written to: /home/jovyan/CppInterOp/build
282.9 ++ nproc --all
282.9 + cmake --build . --parallel 10
282.9 [  7%] Creating directories for 'googletest'
282.9 [  7%] Built target intrinsics_gen
...
314.8 [ 92%] Completed 'googletest'
314.9 [ 92%] Built target googletest
322.9 [ 92%] Built target obj.clangCppInterOp
322.9 [100%] Linking CXX shared library ../libclangCppInterOp.so
323.0 /usr/bin/ld.gold: error: /home/runner/work/xeus-clang-repl/xeus-clang-repl/clang-dev/inst/lib/libLLVMNVPTXCodeGen.a(NVPTXAsmPrinter.cpp.o): incompatible target
323.0 /usr/bin/ld.gold: error: /home/runner/work/xeus-clang-repl/xeus-clang-repl/clang-dev/inst/lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): incompatible target
323.0 /usr/bin/ld.gold: error: /home/runner/work/xeus-clang-repl/xeus-clang-repl/clang-dev/inst/lib/libLLVMNVPTXDesc.a(NVPTXMCTargetDesc.cpp.o): incompatible target
```

Not sure if it's because `gold` isn't smart enough or something else (i.e., I didn't try patching to use `ld` instead).

cc @vgvassilev

### PR DESCRIPTION
**Pull request by mcbarton**
Link to xeus-zmq
Add option to define where cxxopts folder is (Macbook unable to locate folder without) 
Change header file xeus/xserver_zmq.hpp to xeus-zmq/xserver_zmq.hpp 
Add #include <iostream> to include/xeus-clang-repl/xmanager.hpp otherwise errors due to use of std::cerr and others

Once fixes were applied I found I could build on Apple Silicon, but not everything in the xeus-clang-repl notebooks worked.
Fixes https://github.com/compiler-research/xeus-clang-repl/issues/74
Fixes https://github.com/compiler-research/xeus-clang-repl/issues/75

### CODE REVIEW

**Comment by p4vook** [comment]
yeah cmake in this project as a whole needs some work

**Comment by mcbarton** [comment]
@vgvassilev Any suggestions on this pull request? There is almost certainly a better way to do what I have done with cxxopts, but its the only solution I could get to work on my Macbook. After this pull request is approved, I need to make a change to CppInterOp and I should be able to create a build script for those who want to test xeus-clang-repl on their Apple Silicon Macbooks.

**Comment by mcbarton** [comment]
After Github CI workflow failed I realised I need to update Github workflow CI to install xeus-zmq due to my changes, and in the Dockerfile also (and probably a few other places which I haven't realised yet I suspect). Will do this sometime in the next few days. Any other issues raised will be fixed with the commit which fixes this issue.

**Comment by mcbarton** [comment]
I have just pushed a commit to that updates the Dockerfile so that it builds on arm. It should be considered a draft, which I plan to refine, now that I have it building. Other known issues left to do are
1. Test amended CI 
2. Update README

**Comment by mcbarton** [comment]
@vgvassilev This pull request is ready for review.

File: Dockerfile [hunk 1]
```diff
@@ -45,6 +45,7 @@ RUN \
       ###libomp-dev \
     # Other "our" apt installs (development and testing)
       build-essential \
+      clang-15 \
```
Comment (alexander-penev) [inline Dockerfile:50]: In ci.yaml matrix we use clang-runtime==17. Can you use the newer version (17) of the clang runtime here as well? It should be able to since the CI test passes with version 17.

File: Dockerfile [hunk 2]
```diff
@@ -231,26 +240,45 @@ RUN \
...
-    #
+    # Build LLVM (if on arm) & CppInterOp 
+    #  
     sys_incs=$(LC_ALL=C c++ -xc++ -E -v /dev/null 2>&1 | LC_ALL=C sed -ne '/starts here/,/End of/p' | LC_ALL=C sed '/^ /!d' | cut -c2- | tr '\n' ':') && \
     export CPLUS_INCLUDE_PATH="${PATH_TO_LLVM_BUILD}/include/llvm:${PATH_TO_LLVM_BUILD}/include/clange:$CPLUS_INCLUDE_PATH:${sys_incs%:}" && \
     git clone https://github.com/compiler-research/CppInterOp.git && \
+    if [ "$ARCHITECHURE" == "aarch64" ] ; \ 
+    then \
+    export CC=/usr/bin/clang-15 && \
+    export CXX=/usr/bin/clang++-15 && \
```
Comment (alexander-penev) [inline Dockerfile:263]: clang-17?

File: Dockerfile [hunk 3]
```diff
@@ -231,26 +240,45 @@ RUN \
...
+	git clone  --depth=1 --branch release/16.x  https://github.com/llvm/llvm-project.git && \
```
Comment (alexander-penev) [inline Dockerfile:265]: release/17.x

File: Dockerfile [hunk 4]
```diff
@@ -231,26 +240,45 @@ RUN \
...
+	cd ./llvm-project/ && \
+	mkdir build && \
+	export LLVM_DIR=$(pwd) && \
+    compgen -G "../CppInterOp/patches/llvm/clang16-*.patch" > /dev/null && find ../CppInterOp/patches/llvm/clang16-*.patch -printf "%f\n" && git apply ../CppInterOp/patches/llvm/clang16-*.patch && \
```
Comment (alexander-penev) [inline Dockerfile:269]: clang17-*.patch?

File: Dockerfile (hunk 1 above)
Comment (mcbarton) [reply Dockerfile:50]: I used clang-15 as that is the latest version of clang I could find in the apt repository which is available for Ubuntu 22.04 .  Also when building llvm-project I had to build version 16 as building version 17 and using this with CppInterOp would build but fail with this command on an arm architechture (I cannot remember off the top of my head what message it failed with).  It is not currently possible to switch this build of llvm-project to version 17, as although it passes on x86, it doesn't pass on arm (from tests on my local machine).
https://github.com/compiler-research/xeus-clang-repl/blob/ce09338007b7096c52830b2c8da5671707d08aec/Dockerfile#L329

**Review by alexander-penev — APPROVED** [review]
In different places we use different versions of clang. Maybe it's a good idea to standardize and replace them with the latest supported version (17?).
Otherwise, everything else looks good.

File: Dockerfile (hunk 1 above)
Comment (alexander-penev) [reply Dockerfile:50]: Oh, yes. This is a good one. I am misled that conda-forge also has the 17th version, but this is APT.

Comment (mcbarton) [reply Dockerfile:50]: I could put a fixme next the part of the dockerfile which builds llvm-project version 16.x , until the issue using 17.x on arm is resolved (I'd raise it as an issue, so that there is a log of what the error is), and put a fixme next to using Clang-15 from apt (when the next LTS version of Ubuntu comes out April next year this would have the latest version of Clang since its in apt repository for version 23.10 of Ubuntu, so would be a quick fix).

Comment (alexander-penev) [reply Dockerfile:50]: :+1:

**Comment by p4vook** [comment]
There is also an issue where xeus-clang-repl links to its older library instead of the just built one. It isn't specifically related to this PR, but it would be nice to fix.

**Comment by mcbarton** [comment]
Added fixme messages to Dockerfile due to clang-17 issues and build on arm

File: include/xeus-clang-repl/xmanager.hpp [hunk 5]
```diff
@@ -20,6 +20,7 @@
 
 #include "nlohmann/json.hpp"
 
+#include <iostream>
```
Comment (p4vook) [inline include/xeus-clang-repl/xmanager.hpp:23]: Why?

Comment (mcbarton) [reply include/xeus-clang-repl/xmanager.hpp:23]: This is mentioned in the PR description. When building natively on MacOS it would not build without this include due to the use of std::cerr and others

**Review by alexander-penev — APPROVED** [review]
